// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbcxuepgdnrhzdoonqiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiY3h1ZXBnZG5yaHpkb29ucWl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MDU1MTgsImV4cCI6MjA2MTE4MTUxOH0.iivU4D7LY0amSrNTc0LWHqR3l3RVCmS3VPsi-QSAV6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);